name: Deploy jobs
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Azure ML Model Name'
        required: true
        type: string
      model_version:
        description: 'Model Version'
        required: true
        type: string

permissions:
      id-token: write
      contents: read

env:
  MODEL_NAME: ${{ github.event.inputs.model_name || 'my-model' }}
  MODEL_VERSION: ${{ github.event.inputs.model_version || '1' }}

jobs: 
  job-deploy:
    runs-on: [self-hosted, Windows, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: az CLI login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Download model
      run: |
        echo "Downloading model: ${{ env.MODEL_NAME }}, version: ${{ env.MODEL_VERSION }}"
        az ml model download --name ${{ env.MODEL_NAME }} --version ${{ env.MODEL_VERSION }} --download-path "./models" -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} -w ${{ secrets.AZURE_ML_WORKSPACE_NAME }}