name: Deploy jobs
on: 
  push:
    branches:
      - 'main'

permissions:
      id-token: write
      contents: read

jobs: 
  job-deploy:
    runs-on: [self-hosted, Windows, x64]
    steps:
    - name: az CLI login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Install ML extension for az command
      run: az extension add -n ml -y
    - name: Create ML Job
      run: |
        az account show > C:\Users\sqladmin\hoge3.txt
        az ml model download --name walmart --version 1 --download-path "./models" -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} -w ${{ secrets.AZURE_ML_WORKSPACE_NAME }}